(() => {
  'use strict';
  const cfg=window.SASUF_ADMIN_CONFIG||{}, endpoint=cfg.apiEndpoint, tokenKey='sasuf_admin_token_v17'; let currentSite='ALL', currentQuality='ALL', currentFreeTextKey='worthUsing', freeTextRows=[], freeTextPage=1; const FREE_TEXT_PAGE_SIZE=25;
  const freeTextLabels={worthUsing:'When more capable GenAI is justified vs. a simpler option',guidanceWanted:'What universities should consider in student support'};
  const $=id=>document.getElementById(id), loginView=$('loginView'), dashboardView=$('dashboardView'), loginForm=$('loginForm'), loginError=$('loginError');
  if(cfg.title)$('pageTitle').textContent=cfg.title;
  const token=()=>sessionStorage.getItem(tokenKey)||''; const setToken=v=>v?sessionStorage.setItem(tokenKey,v):sessionStorage.removeItem(tokenKey);
  async function api(body,blob=false){const headers={'Content-Type':'application/json'};if(token())headers.Authorization='Bearer '+token();const r=await fetch(endpoint,{method:'POST',headers,body:JSON.stringify(body),cache:'no-store'});if(r.status===401){setToken('');showLogin();throw new Error('Your admin session has expired. Please sign in again.');}if(!r.ok){let m='Request failed.';try{const d=await r.json();if(d.error)m=d.error;}catch(_){}throw new Error(m);}return blob?r.blob():r.json();}
  function showLogin(){dashboardView.hidden=true;loginView.hidden=false;$('password').value='';setTimeout(()=>$('password').focus(),20)} function showDashboard(){loginView.hidden=true;dashboardView.hidden=false}
  loginForm.addEventListener('submit',async e=>{e.preventDefault();loginError.hidden=true;try{const d=await api({action:'login',password:$('password').value});setToken(d.token);showDashboard();await loadStats();}catch(err){loginError.textContent=err.message||'Could not sign in.';loginError.hidden=false;}});
  document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',async()=>{currentSite=b.dataset.site;freeTextPage=1;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));await loadStats();}));
  const qualityFilter=$('qualityFilter'); if(qualityFilter)qualityFilter.addEventListener('change',async()=>{currentQuality=qualityFilter.value||'ALL';freeTextPage=1;await loadStats();});
  document.querySelectorAll('.free-text-tab').forEach(b=>b.addEventListener('click',()=>{currentFreeTextKey=b.dataset.freeKey;freeTextPage=1;document.querySelectorAll('.free-text-tab').forEach(x=>x.classList.toggle('active',x===b));renderFreeText();}));
  const freeTextSearch=$('freeTextSearch'), freeTextSite=$('freeTextSite'), freeTextInstitution=$('freeTextInstitution'), freeTextPrev=$('freeTextPrev'), freeTextNext=$('freeTextNext');
  if(freeTextSearch)freeTextSearch.addEventListener('input',()=>{freeTextPage=1;renderFreeText();});
  if(freeTextSite)freeTextSite.addEventListener('change',()=>{freeTextPage=1;updateFreeTextInstitutionOptions();renderFreeText();});
  if(freeTextInstitution)freeTextInstitution.addEventListener('change',()=>{freeTextPage=1;renderFreeText();});
  if(freeTextPrev)freeTextPrev.addEventListener('click',()=>{if(freeTextPage>1){freeTextPage--;renderFreeText();scrollFreeTextIntoView();}});
  if(freeTextNext)freeTextNext.addEventListener('click',()=>{freeTextPage++;renderFreeText();scrollFreeTextIntoView();});
  $('refreshBtn').addEventListener('click',loadStats); $('logoutBtn').addEventListener('click',()=>{setToken('');showLogin();});
  $('exportFlatBtn').addEventListener('click',()=>downloadExport('export_flat','sasuf_analysis')); $('exportRawBtn').addEventListener('click',()=>downloadExport('export_raw','sasuf_raw'));
  const clearDbBtn=$('clearDbBtn'); if(clearDbBtn)clearDbBtn.addEventListener('click',clearDatabase);
  async function downloadExport(action,prefix){try{showStatus('Preparing CSV…');const blob=await api({action,site:currentSite,quality_filter:action==='export_flat'?currentQuality:'ALL'},true),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${prefix}_${currentSite.toLowerCase()}_${new Date().toISOString().slice(0,10)}.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);hideStatus();}catch(err){showStatus(err.message,true);}}
  async function loadStats(){try{showStatus('Loading live statistics…');const results=await Promise.all([api({action:'stats',site:currentSite,quality_filter:currentQuality}),api({action:'free_text',site:currentSite,quality_filter:currentQuality})]);render(results[0]);freeTextRows=Array.isArray(results[1].rows)?results[1].rows:[];freeTextPage=1;updateFreeTextFilterOptions();renderFreeText();hideStatus();}catch(err){showStatus(err.message,true);}}
  async function clearDatabase(){
    if(!window.confirm('This will permanently delete ALL survey responses from both the Sweden and South Africa tables, including responses from every survey version. This cannot be undone. Continue?'))return;
    const phrase=window.prompt('Type DELETE ALL RESPONSES to confirm:');
    if(phrase===null)return;
    if(phrase!=='DELETE ALL RESPONSES'){window.alert('Confirmation text did not match. Nothing was deleted.');return;}
    clearDbBtn.disabled=true;
    try{showStatus('Deleting all survey responses…');const d=await api({action:'clear_database',confirmation:phrase});const se=d.deleted&&d.deleted.SE!=null?d.deleted.SE:0,sa=d.deleted&&d.deleted.SA!=null?d.deleted.SA:0;window.alert(`Database emptied. Deleted ${se} Sweden response(s) and ${sa} South Africa response(s).`);await loadStats();}
    catch(err){showStatus(err.message,true);}finally{clearDbBtn.disabled=false;}
  }
  function render(d){const s=d.stats;$('kpiShown').textContent=s.n;$('kpiShownSub').textContent=(currentSite==='ALL'?'SE + SA':currentSite)+(currentQuality==='CLEAN'?' · flagged hidden':currentQuality==='FLAGGED'?' · flagged only':'');$('kpiSE').textContent=d.totals.SE;$('kpiSA').textContent=d.totals.SA;$('kpiTime').textContent=s.avg_completion_minutes==null?'—':Number(s.avg_completion_minutes).toFixed(1)+'m';$('kpiLatest').textContent='median: '+(s.median_completion_minutes==null?'—':Number(s.median_completion_minutes).toFixed(1)+'m');renderQuality(d.quality_summary||{});
    renderBars('institutions',s.institutions);renderBars('studyLevels',s.study_levels);renderBars('disciplines',s.disciplines);renderAgeSummary(s.age_summary);renderBars('genders',s.genders);renderBars('programmeLanguageFirst',s.programme_language_first);renderBars('useFrequency',s.use_frequency);renderBars('purposes',translateCounts(s.purposes,d.purpose_labels));renderBars('formalTraining',s.formal_training);renderBars('paidAccess',s.paid_access);renderBars('institutionalAccess',s.institutional_access);renderBars('resourceAwareness',s.resource_awareness);renderBars('localContextMismatch',s.local_context_mismatch);renderBaseline(s.baseline_scales,d.baseline_labels);renderAssistance(s.assistance_distribution,d.scenario_labels);renderScenarioTable(s.scenario_means,d.scenario_labels,d.measure_labels);renderBars('decisionFactors',translateCounts(s.decision_factors,d.reason_labels));renderRecent(d.recent||[]);$('comparisonSection').hidden=currentSite!=='ALL';if(currentSite==='ALL')renderComparison(d.comparison,d.scenario_labels);
  }
  function renderQuality(q){const total=Number(q.total||0),flagged=Number(q.flagged||0),timed=Number(q.timing_available||0);$('qualityFlagged').textContent=total?`${flagged} / ${total}`:'—';$('qualityFlaggedSub').textContent=total?`${(flagged/total*100).toFixed(1)}% currently flagged for review.`:'No responses yet.';$('qualityTiming').textContent=total?`${timed} / ${total}`:'—';$('qualityTimingSub').textContent=total?`${(timed/total*100).toFixed(1)}% have active-time paradata.`:'No responses yet.';$('qualityMedian').textContent=q.median_active_minutes==null?'—':Number(q.median_active_minutes).toFixed(1)+'m';const site=q.site_median_active_minutes||{};$('qualityMedianSub').textContent=`SE ${site.SE==null?'—':Number(site.SE).toFixed(1)+'m'} · SA ${site.SA==null?'—':Number(site.SA).toFixed(1)+'m'}`;const labels={very_fast_absolute:'Active time < 5 min',very_fast_relative:'< 1/3 site median',scenario_rushing:'Scenario pages rushed',straightlining:'Scenario straightlining',dominant_rating:'≥90% same rating',duplicate_pattern:'Exact duplicate pattern'};renderBars('qualityReasons',translateCounts(q.reasons||{},labels));}
  function renderAgeSummary(summary){const root=$('ageSummary');const s=summary||{};if(!s.n){root.innerHTML='<div class="empty">No numeric age data yet.</div>';return;}root.innerHTML=`<div class="age-stats"><div><span>N</span><strong>${Number(s.n)}</strong></div><div><span>Mean</span><strong>${fmt(s.mean)}</strong></div><div><span>Median</span><strong>${fmt(s.median)}</strong></div><div><span>SD</span><strong>${fmt(s.sd)}</strong></div><div><span>Variance</span><strong>${fmt(s.variance)}</strong></div><div><span>Range</span><strong>${fmt0(s.min)}–${fmt0(s.max)}</strong></div></div>`;}
  function fmt0(v){return v==null||Number.isNaN(Number(v))?'—':String(Math.round(Number(v)))}
  function renderBars(id,counts){const root=$(id);root.innerHTML='';const entries=Object.entries(counts||{}).sort((a,b)=>b[1]-a[1]);if(!entries.length){root.innerHTML='<div class="empty">No data yet.</div>';return;}const max=Math.max(...entries.map(e=>e[1]),1);entries.forEach(([label,count])=>{const row=document.createElement('div');row.className='bar-row';row.innerHTML=`<div class="bar-label" title="${esc(label)}">${esc(label)}</div><div class="bar-track"><div class="bar-fill" style="width:${(count/max*100).toFixed(1)}%"></div></div><div class="bar-count">${count}</div>`;root.appendChild(row);});}
  function renderBaseline(values,labels){const root=$('baselineRatings');root.innerHTML='';Object.entries(labels||{}).forEach(([key,label])=>{const v=values&&values[key]!=null?Number(values[key]):null,row=document.createElement('div');row.className='metric-row';row.innerHTML=`<div>${esc(label)}</div><div class="score-track"><div class="score-fill" style="width:${v==null?0:(v/7*100).toFixed(1)}%"></div></div><div class="score">${fmt(v)}</div>`;root.appendChild(row);});}
  function renderAssistance(dist,labels){const t=$('assistanceTable');let h='<thead><tr><th>Scenario</th><th>N</th><th>1 No AI</th><th>2 Conventional</th><th>3 Specialized AI</th><th>4 GenAI</th><th>5 Advanced / reasoning</th></tr></thead><tbody>';Object.entries(labels||{}).forEach(([sid,label])=>{const d=dist?.[sid]||{},n=[1,2,3,4,5].reduce((a,k)=>a+Number(d[k]||0),0);h+=`<tr><td><strong>${esc(label)}</strong></td><td class="num">${n||'—'}</td>`;[1,2,3,4,5].forEach(k=>{const pct=n?Number(d[k]||0)/n*100:null;h+=`<td class="num">${pct==null?'—':pct.toFixed(1)+'%'}</td>`;});h+='</tr>';});t.innerHTML=h+'</tbody>';}
  function renderScenarioTable(means,labels,measures){const t=$('scenarioTable');let h='<thead><tr><th>Scenario</th>'+Object.values(measures||{}).map(x=>`<th>${esc(x)}</th>`).join('')+'</tr></thead><tbody>';Object.entries(labels||{}).forEach(([sid,label])=>{h+=`<tr><td><strong>${esc(label)}</strong></td>`;Object.keys(measures||{}).forEach(mid=>h+=`<td class="num">${fmt(means?.[sid]?.[mid])}</td>`);h+='</tr>';});t.innerHTML=h+'</tbody>';}
  function renderComparison(rows,labels){const t=$('comparisonTable');let h='<thead><tr><th>Scenario</th><th>SE % GenAI/advanced</th><th>SA % GenAI/advanced</th><th>Δ percentage points</th><th>SE trade-off</th><th>SA trade-off</th><th>Trade-off Δ SE−SA</th><th>SE meaningful value</th><th>SA meaningful value</th></tr></thead><tbody>';Object.keys(labels||{}).forEach(sid=>{const r=rows?.[sid]||{};h+=`<tr><td><strong>${esc(labels[sid])}</strong></td><td class="num">${pct(r.se_high_ai_share)}</td><td class="num">${pct(r.sa_high_ai_share)}</td><td class="num">${signedPct(r.high_ai_share_difference)}</td><td class="num">${fmt(r.se_tradeoff)}</td><td class="num">${fmt(r.sa_tradeoff)}</td><td class="num">${signed(r.tradeoff_difference)}</td><td class="num">${fmt(r.se_value)}</td><td class="num">${fmt(r.sa_value)}</td></tr>`;});t.innerHTML=h+'</tbody>';}
  function renderRecent(rows){const t=$('recentTable');let h='<thead><tr><th>Site</th><th>Submitted</th><th>Active time</th><th>Quality</th><th>Institution</th><th>Study level</th><th>Discipline</th><th>Survey version</th></tr></thead><tbody>';if(!rows.length)h+='<tr><td colspan="8" class="empty">No responses yet.</td></tr>';rows.forEach(r=>{const q=r.quality_flagged?`<span class="quality-badge flagged" title="${esc((r.quality_flags||[]).join('; '))}">Review</span>`:'<span class="quality-badge clean">OK</span>';h+=`<tr><td><span class="site-badge site-${esc(r.site)}">${esc(r.site)}</span></td><td>${esc(r.submitted_at||'—')}</td><td class="num">${r.active_minutes==null?'—':Number(r.active_minutes).toFixed(1)+'m'}</td><td>${q}</td><td>${esc(r.institution||'—')}</td><td>${esc(r.study_level||'—')}</td><td>${esc(r.discipline||'—')}</td><td>${esc(r.survey_version||'—')}</td></tr>`;});t.innerHTML=h+'</tbody>';}
  function updateFreeTextFilterOptions(){
    if(!freeTextSite||!freeTextInstitution)return;
    const previousSite=freeTextSite.value||'ALL';
    const sites=[...new Set(freeTextRows.map(r=>String(r.site||'').trim()).filter(Boolean))].sort();
    freeTextSite.innerHTML='<option value="ALL">All available sites</option>'+sites.map(site=>`<option value="${esc(site)}">${site==='SE'?'Sweden (SE)':site==='SA'?'South Africa (SA)':esc(site)}</option>`).join('');
    freeTextSite.value=sites.includes(previousSite)?previousSite:'ALL';
    updateFreeTextInstitutionOptions();
  }
  function updateFreeTextInstitutionOptions(){
    if(!freeTextInstitution)return;
    const previous=freeTextInstitution.value||'ALL', site=freeTextSite?freeTextSite.value:'ALL';
    const institutions=[...new Set(freeTextRows.filter(r=>site==='ALL'||r.site===site).map(r=>String(r.institution||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b));
    freeTextInstitution.innerHTML='<option value="ALL">All institutions</option>'+institutions.map(name=>`<option value="${esc(name)}">${esc(name)}</option>`).join('');
    freeTextInstitution.value=institutions.includes(previous)?previous:'ALL';
  }
  function freeTextFilteredRows(key){
    const site=freeTextSite?freeTextSite.value:'ALL', institution=freeTextInstitution?freeTextInstitution.value:'ALL', query=(freeTextSearch?freeTextSearch.value:'').trim().toLowerCase();
    return freeTextRows.filter(r=>{
      const text=String(r?.texts?.[key]||'').trim();
      if(!text)return false;
      if(site!=='ALL'&&r.site!==site)return false;
      if(institution!=='ALL'&&r.institution!==institution)return false;
      if(query&&!text.toLowerCase().includes(query))return false;
      return true;
    });
  }
  function scrollFreeTextIntoView(){const section=$('freeTextSummary')?.closest('.section');if(section)section.scrollIntoView({behavior:'smooth',block:'start'});}
  function renderFreeText(){
    const root=$('freeTextList'); if(!root)return;
    document.querySelectorAll('[data-free-count]').forEach(el=>{const key=el.dataset.freeCount;el.textContent=freeTextFilteredRows(key).length;});
    const rows=freeTextFilteredRows(currentFreeTextKey), total=rows.length, pages=Math.max(1,Math.ceil(total/FREE_TEXT_PAGE_SIZE));
    if(freeTextPage>pages)freeTextPage=pages;if(freeTextPage<1)freeTextPage=1;
    const start=(freeTextPage-1)*FREE_TEXT_PAGE_SIZE, pageRows=rows.slice(start,start+FREE_TEXT_PAGE_SIZE), summary=$('freeTextSummary'), pageInfo=$('freeTextPageInfo');
    if(summary)summary.textContent=total?`Showing ${start+1}–${Math.min(start+FREE_TEXT_PAGE_SIZE,total)} of ${total} matching response${total===1?'':'s'}.`:'No matching responses.';
    if(pageInfo)pageInfo.textContent=`Page ${freeTextPage} of ${pages}`;
    if(freeTextPrev)freeTextPrev.disabled=freeTextPage<=1||total===0;
    if(freeTextNext)freeTextNext.disabled=freeTextPage>=pages||total===0;
    const pager=freeTextPrev?.parentElement;if(pager)pager.hidden=total<=FREE_TEXT_PAGE_SIZE;
    if(!total){root.innerHTML=`<div class="free-text-empty">No responses for “${esc(freeTextLabels[currentFreeTextKey]||'this question')}” match the current filters.</div>`;return;}
    root.innerHTML=pageRows.map(r=>{const parts=[r.submitted_at||'',r.active_minutes==null?'':Number(r.active_minutes).toFixed(1)+'m active',r.institution||'',r.study_level||'',r.discipline||''].filter(Boolean);const quality=r.quality_flagged?`<span class="quality-badge flagged" title="${esc((r.quality_flags||[]).join('; '))}">Review</span>`:'<span class="quality-badge clean">OK</span>';return `<article class="free-text-card"><div class="free-text-meta"><span class="site-badge site-${esc(r.site)}">${esc(r.site)}</span><strong>Response #${esc(r.response_id)}</strong>${quality}${parts.map(x=>`<span class="meta-sep">·</span><span>${esc(x)}</span>`).join('')}</div><p class="free-text-body">${esc(r.texts[currentFreeTextKey])}</p></article>`;}).join('');
  }
  function translateCounts(counts,labels){const out={};Object.keys(labels||{}).forEach(k=>out[labels[k]]=counts?.[k]||0);return out;} function fmt(v){return v==null||Number.isNaN(Number(v))?'—':Number(v).toFixed(2)} function signed(v){if(v==null||Number.isNaN(Number(v)))return'—';const n=Number(v);return(n>=0?'+':'')+n.toFixed(2)} function pct(v){return v==null||Number.isNaN(Number(v))?'—':Number(v).toFixed(1)+'%'} function signedPct(v){if(v==null||Number.isNaN(Number(v)))return'—';const n=Number(v);return(n>=0?'+':'')+n.toFixed(1)+' pp'} function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))} function showStatus(m,e=false){const el=$('statusMessage');el.textContent=m;el.className='status'+(e?' error':'');el.hidden=false} function hideStatus(){$('statusMessage').hidden=true}
  if(token()){showDashboard();loadStats();}else showLogin();
})();
