(() => {
  'use strict';
  const cfg=window.SASUF_ADMIN_CONFIG||{}, endpoint=cfg.apiEndpoint, tokenKey='sasuf_admin_token_v10'; let currentSite='ALL';
  const $=id=>document.getElementById(id), loginView=$('loginView'), dashboardView=$('dashboardView'), loginForm=$('loginForm'), loginError=$('loginError');
  if(cfg.title)$('pageTitle').textContent=cfg.title;
  const token=()=>sessionStorage.getItem(tokenKey)||''; const setToken=v=>v?sessionStorage.setItem(tokenKey,v):sessionStorage.removeItem(tokenKey);
  async function api(body,blob=false){const headers={'Content-Type':'application/json'};if(token())headers.Authorization='Bearer '+token();const r=await fetch(endpoint,{method:'POST',headers,body:JSON.stringify(body),cache:'no-store'});if(r.status===401){setToken('');showLogin();throw new Error('Your admin session has expired. Please sign in again.');}if(!r.ok){let m='Request failed.';try{const d=await r.json();if(d.error)m=d.error;}catch(_){}throw new Error(m);}return blob?r.blob():r.json();}
  function showLogin(){dashboardView.hidden=true;loginView.hidden=false;$('password').value='';setTimeout(()=>$('password').focus(),20)} function showDashboard(){loginView.hidden=true;dashboardView.hidden=false}
  loginForm.addEventListener('submit',async e=>{e.preventDefault();loginError.hidden=true;try{const d=await api({action:'login',password:$('password').value});setToken(d.token);showDashboard();await loadStats();}catch(err){loginError.textContent=err.message||'Could not sign in.';loginError.hidden=false;}});
  document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',async()=>{currentSite=b.dataset.site;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));await loadStats();}));
  $('refreshBtn').addEventListener('click',loadStats); $('logoutBtn').addEventListener('click',()=>{setToken('');showLogin();});
  $('exportFlatBtn').addEventListener('click',()=>downloadExport('export_flat','sasuf_analysis')); $('exportRawBtn').addEventListener('click',()=>downloadExport('export_raw','sasuf_raw'));
  async function downloadExport(action,prefix){try{showStatus('Preparing CSV…');const blob=await api({action,site:currentSite},true),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${prefix}_${currentSite.toLowerCase()}_${new Date().toISOString().slice(0,10)}.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);hideStatus();}catch(err){showStatus(err.message,true);}}
  async function loadStats(){try{showStatus('Loading live statistics…');const d=await api({action:'stats',site:currentSite});render(d);hideStatus();}catch(err){showStatus(err.message,true);}}
  function render(d){const s=d.stats;$('kpiShown').textContent=s.n;$('kpiShownSub').textContent=currentSite==='ALL'?'SE + SA':currentSite;$('kpiSE').textContent=d.totals.SE;$('kpiSA').textContent=d.totals.SA;$('kpiTime').textContent=s.avg_completion_minutes==null?'—':Number(s.avg_completion_minutes).toFixed(1)+'m';$('kpiLatest').textContent='latest: '+(s.latest||'—');
    renderBars('institutions',s.institutions);renderBars('studyLevels',s.study_levels);renderBars('programmeYears',s.programme_years);renderBars('disciplines',s.disciplines);renderBars('ageGroups',s.age_groups);renderBars('genders',s.genders);renderBars('programmeLanguageFirst',s.programme_language_first);renderBars('preUniversitySameCountry',s.pre_university_same_country);renderBars('useFrequency',s.use_frequency);renderBars('purposes',translateCounts(s.purposes,d.purpose_labels));renderBars('guidance',s.guidance);renderBars('formalTraining',s.formal_training);renderBars('paidAccess',s.paid_access);renderBars('institutionalAccess',s.institutional_access);renderBars('resourceAwareness',s.resource_awareness);renderBars('localContextMismatch',s.local_context_mismatch);renderBaseline(s.baseline_scales,d.baseline_labels);renderAssistance(s.assistance_distribution,d.scenario_labels);renderScenarioTable(s.scenario_means,d.scenario_labels,d.measure_labels);renderBars('decisionFactors',translateCounts(s.decision_factors,d.reason_labels));renderRecent(d.recent||[]);$('comparisonSection').hidden=currentSite!=='ALL';if(currentSite==='ALL')renderComparison(d.comparison,d.scenario_labels);
  }
  function renderBars(id,counts){const root=$(id);root.innerHTML='';const entries=Object.entries(counts||{}).sort((a,b)=>b[1]-a[1]);if(!entries.length){root.innerHTML='<div class="empty">No data yet.</div>';return;}const max=Math.max(...entries.map(e=>e[1]),1);entries.forEach(([label,count])=>{const row=document.createElement('div');row.className='bar-row';row.innerHTML=`<div class="bar-label" title="${esc(label)}">${esc(label)}</div><div class="bar-track"><div class="bar-fill" style="width:${(count/max*100).toFixed(1)}%"></div></div><div class="bar-count">${count}</div>`;root.appendChild(row);});}
  function renderBaseline(values,labels){const root=$('baselineRatings');root.innerHTML='';Object.entries(labels||{}).forEach(([key,label])=>{const v=values&&values[key]!=null?Number(values[key]):null,row=document.createElement('div');row.className='metric-row';row.innerHTML=`<div>${esc(label)}</div><div class="score-track"><div class="score-fill" style="width:${v==null?0:(v/7*100).toFixed(1)}%"></div></div><div class="score">${fmt(v)}</div>`;root.appendChild(row);});}
  function renderAssistance(dist,labels){const t=$('assistanceTable');let h='<thead><tr><th>Scenario</th><th>N</th><th>1 No AI</th><th>2 Conventional</th><th>3 Specialized AI</th><th>4 GenAI</th><th>5 Advanced / reasoning</th></tr></thead><tbody>';Object.entries(labels||{}).forEach(([sid,label])=>{const d=dist?.[sid]||{},n=[1,2,3,4,5].reduce((a,k)=>a+Number(d[k]||0),0);h+=`<tr><td><strong>${esc(label)}</strong></td><td class="num">${n||'—'}</td>`;[1,2,3,4,5].forEach(k=>{const pct=n?Number(d[k]||0)/n*100:null;h+=`<td class="num">${pct==null?'—':pct.toFixed(1)+'%'}</td>`;});h+='</tr>';});t.innerHTML=h+'</tbody>';}
  function renderScenarioTable(means,labels,measures){const t=$('scenarioTable');let h='<thead><tr><th>Scenario</th>'+Object.values(measures||{}).map(x=>`<th>${esc(x)}</th>`).join('')+'</tr></thead><tbody>';Object.entries(labels||{}).forEach(([sid,label])=>{h+=`<tr><td><strong>${esc(label)}</strong></td>`;Object.keys(measures||{}).forEach(mid=>h+=`<td class="num">${fmt(means?.[sid]?.[mid])}</td>`);h+='</tr>';});t.innerHTML=h+'</tbody>';}
  function renderComparison(rows,labels){const t=$('comparisonTable');let h='<thead><tr><th>Scenario</th><th>SE % GenAI/advanced</th><th>SA % GenAI/advanced</th><th>Δ percentage points</th><th>SE trade-off</th><th>SA trade-off</th><th>Trade-off Δ SE−SA</th><th>SE appropriate</th><th>SA appropriate</th></tr></thead><tbody>';Object.keys(labels||{}).forEach(sid=>{const r=rows?.[sid]||{};h+=`<tr><td><strong>${esc(labels[sid])}</strong></td><td class="num">${pct(r.se_high_ai_share)}</td><td class="num">${pct(r.sa_high_ai_share)}</td><td class="num">${signedPct(r.high_ai_share_difference)}</td><td class="num">${fmt(r.se_tradeoff)}</td><td class="num">${fmt(r.sa_tradeoff)}</td><td class="num">${signed(r.tradeoff_difference)}</td><td class="num">${fmt(r.se_appropriate)}</td><td class="num">${fmt(r.sa_appropriate)}</td></tr>`;});t.innerHTML=h+'</tbody>';}
  function renderRecent(rows){const t=$('recentTable');let h='<thead><tr><th>Site</th><th>Submitted</th><th>Institution</th><th>Study level</th><th>Discipline</th><th>Survey version</th></tr></thead><tbody>';if(!rows.length)h+='<tr><td colspan="6" class="empty">No responses yet.</td></tr>';rows.forEach(r=>h+=`<tr><td><span class="site-badge site-${esc(r.site)}">${esc(r.site)}</span></td><td>${esc(r.submitted_at||'—')}</td><td>${esc(r.institution||'—')}</td><td>${esc(r.study_level||'—')}</td><td>${esc(r.discipline||'—')}</td><td>${esc(r.survey_version||'—')}</td></tr>`);t.innerHTML=h+'</tbody>';}
  function translateCounts(counts,labels){const out={};Object.keys(labels||{}).forEach(k=>out[labels[k]]=counts?.[k]||0);return out;} function fmt(v){return v==null||Number.isNaN(Number(v))?'—':Number(v).toFixed(2)} function signed(v){if(v==null||Number.isNaN(Number(v)))return'—';const n=Number(v);return(n>=0?'+':'')+n.toFixed(2)} function pct(v){return v==null||Number.isNaN(Number(v))?'—':Number(v).toFixed(1)+'%'} function signedPct(v){if(v==null||Number.isNaN(Number(v)))return'—';const n=Number(v);return(n>=0?'+':'')+n.toFixed(1)+' pp'} function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))} function showStatus(m,e=false){const el=$('statusMessage');el.textContent=m;el.className='status'+(e?' error':'');el.hidden=false} function hideStatus(){$('statusMessage').hidden=true}
  if(token()){showDashboard();loadStats();}else showLogin();
})();
